@echo off
echo Starting ViT Vision Server...
echo Installing PyTorch with CUDA support...
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
echo Installing other requirements...
pip install transformers pillow flask flask-cors
python vit_server.py